//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Plugin.Survey.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Survey_Web
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Survey_Web()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPI.Plugin.Survey.Properties.Resources.Survey.Web", typeof(Resources_Survey_Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string Network_Index_Clear
        {
            get
            {
                return ResourceManager.GetString("Network_Index_Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have chosen to clear all entered data. You will have to restart the survey from the beginning. Do you wish to start over?.
        /// </summary>
        public static string Network_Index_ClearMessage
        {
            get
            {
                return ResourceManager.GetString("Network_Index_ClearMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List Your Network Contacts.
        /// </summary>
        public static string Network_Index_Title
        {
            get
            {
                return ResourceManager.GetString("Network_Index_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Who helps keep you abreast of key trends (priorities, constraints, or capabilities) in your organization?
        ///
        ///Who helps you understand the strategic landscape or competitive environment (opportunities and challenges) that impact your area of responsibility?.
        /// </summary>
        public static string Network_Paragraph1
        {
            get
            {
                return ResourceManager.GetString("Network_Paragraph1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your Strategic Network: Scanning and Sensing.
        /// </summary>
        public static string Network_Paragraph1_Title
        {
            get
            {
                return ResourceManager.GetString("Network_Paragraph1_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Who do you rely upon to get your job done? Consider people who have provided you and your team with key advice, information, support, or resources pertaining to your current job..
        /// </summary>
        public static string Network_Paragraph2
        {
            get
            {
                return ResourceManager.GetString("Network_Paragraph2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your Operational Network: Getting the Work Done.
        /// </summary>
        public static string Network_Paragraph2_Title
        {
            get
            {
                return ResourceManager.GetString("Network_Paragraph2_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Who has contributed to your professional development in the last couple of years (e.g., provided coaching, protection, exposure, social support)?.
        /// </summary>
        public static string Network_Paragraph3
        {
            get
            {
                return ResourceManager.GetString("Network_Paragraph3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your Developmental Network: Professional &amp; Career Development.
        /// </summary>
        public static string Network_Paragraph3_Title
        {
            get
            {
                return ResourceManager.GetString("Network_Paragraph3_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string NetworkRelationship_Index_Close
        {
            get
            {
                return ResourceManager.GetString("NetworkRelationship_Index_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string NetworkRelationShip_Index_ContactName
        {
            get
            {
                return ResourceManager.GetString("NetworkRelationShip_Index_ContactName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Distant.
        /// </summary>
        public static string NetworkRelationship_Index_Distant
        {
            get
            {
                return ResourceManager.GetString("NetworkRelationship_Index_Distant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not Very Close.
        /// </summary>
        public static string NetworkRelationship_Index_NotVeryClose
        {
            get
            {
                return ResourceManager.GetString("NetworkRelationship_Index_NotVeryClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network Characteristics: Closeness of Relationships.
        /// </summary>
        public static string NetworkRelationship_Index_Title
        {
            get
            {
                return ResourceManager.GetString("NetworkRelationship_Index_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Very Close.
        /// </summary>
        public static string NetworkRelationship_Index_VeryClose
        {
            get
            {
                return ResourceManager.GetString("NetworkRelationship_Index_VeryClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please assess the quality of each relationship in your network. 
        ///
        ///Rate the closeness of your relationship with each person along a scale from “very close” to “distant,” noting that “very close” relationships are characterized by high degrees of mutual trust and commitment, while “distant” relationships are characterized by not knowing the person very well..
        /// </summary>
        public static string NetworkRelationship_Paragraph
        {
            get
            {
                return ResourceManager.GetString("NetworkRelationship_Paragraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Age Group.
        /// </summary>
        public static string Profile_Index_AgeGroup
        {
            get
            {
                return ResourceManager.GetString("Profile_Index_AgeGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are about to complete your survey. Once submitted, you will no longer be able to view or edit your answers. Do you wish to submit your survey?.
        /// </summary>
        public static string Profile_Index_CompletePopUp
        {
            get
            {
                return ResourceManager.GetString("Profile_Index_CompletePopUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Complete Survey.
        /// </summary>
        public static string Profile_Index_CompleteSurvey
        {
            get
            {
                return ResourceManager.GetString("Profile_Index_CompleteSurvey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Profile_Index_Gender
        {
            get
            {
                return ResourceManager.GetString("Profile_Index_Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Profile_Index_Nationality
        {
            get
            {
                return ResourceManager.GetString("Profile_Index_Nationality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Answering the questions below can help us provide you with a more personalized analysis of your network. Although we may use the data to conduct group analyses to establish norms for this assessment tool, should you choose to respond, your answers will remain strictly confidential..
        /// </summary>
        public static string Profile_Index_Paragraph
        {
            get
            {
                return ResourceManager.GetString("Profile_Index_Paragraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you work in your native Language.
        /// </summary>
        public static string Profile_Index_SpeakNative
        {
            get
            {
                return ResourceManager.GetString("Profile_Index_SpeakNative", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Personal and Demographic Questions (Optional).
        /// </summary>
        public static string Profile_Index_Title
        {
            get
            {
                return ResourceManager.GetString("Profile_Index_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Age Group.
        /// </summary>
        public static string RelationShipDemo_Index_AgeGroup
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_AgeGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Business unit, division, or office.
        /// </summary>
        public static string RelationShipDemo_Index_BusinessUnit
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_BusinessUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company or organization.
        /// </summary>
        public static string RelationShipDemo_Index_Firm
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_Firm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Functional or product area.
        /// </summary>
        public static string RelationShipDemo_Index_FunctionArea
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_FunctionArea", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string RelationShipDemo_Index_Gender
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_Gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Native Language.
        /// </summary>
        public static string RelationShipDemo_Index_Language
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_Language", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Native Language.
        /// </summary>
        public static string RelationShipDemo_Index_RegionFrom
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_RegionFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Same Nationality.
        /// </summary>
        public static string RelationShipDemo_Index_Nationality
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_Nationality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After this point, you should not add to or edit your network contacts. Do you wish to continue?.
        /// </summary>
        public static string RelationShipDemo_Index_NextMessage
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_NextMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Using the drop-down menus, select the responses that best describe each person in your network. Answer to the best of your knowledge..
        /// </summary>
        public static string RelationShipDemo_Index_Paragraph
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_Paragraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Same Race.
        /// </summary>
        public static string RelationShipDemo_Index_Race
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_Race", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Relationship to me.
        /// </summary>
        public static string RelationShipDemo_Index_RelationShip
        {
            get
            {
                return ResourceManager.GetString("RelationShipDemo_Index_RelationShip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network Characteristics: Breadth &amp; Diversity.
        /// </summary>
        public static string RelationshipDemo_Index_Title
        {
            get
            {
                return ResourceManager.GetString("RelationshipDemo_Index_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Indicate who knows whom, by placing a checkmark in the cells corresponding to each acquainted pair. Leave a cell blank if the pair do not know each other, or if you do not know whether they know each other..
        /// </summary>
        public static string RelDensity_Index_Paragraph
        {
            get
            {
                return ResourceManager.GetString("RelDensity_Index_Paragraph", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Who Knows Whom.
        /// </summary>
        public static string RelDensity_Index_Title
        {
            get
            {
                return ResourceManager.GetString("RelDensity_Index_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have projects without emails setup, please visit Email Section.
        /// </summary>
        public static string Survey_Index_NoEmail
        {
            get
            {
                return ResourceManager.GetString("Survey_Index_NoEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to -Program-.
        /// </summary>
        public static string Survey_Index_SearchDropDown
        {
            get
            {
                return ResourceManager.GetString("Survey_Index_SearchDropDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send Invites.
        /// </summary>
        public static string Survey_Index_SendInvites
        {
            get
            {
                return ResourceManager.GetString("Survey_Index_SendInvites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send Reminders.
        /// </summary>
        public static string Survey_Index_SendReminders
        {
            get
            {
                return ResourceManager.GetString("Survey_Index_SendReminders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        public static string Survey_Index_Title
        {
            get
            {
                return ResourceManager.GetString("Survey_Index_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string Survey_SurveyComplete_CompleteHeader
        {
            get
            {
                return ResourceManager.GetString("Survey_SurveyComplete_CompleteHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This instrument is based on Herminia Ibarra’s “Network Assessment Exercise: Executive Version” (Harvard Business School Publishing, product #9-497-003), and the works of R. S. Burt, Tiziana Casciaro, Morten Hansen, Monica Higgins, Linda Hill, and David Thomas..
        /// </summary>
        public static string Survey_SurveyComplete_CompleteSubFooter
        {
            get
            {
                return ResourceManager.GetString("Survey_SurveyComplete_CompleteSubFooter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thank you for taking the time to complete the Network Assessment Survey. You will be contacted with your results. If you have any questions, please contact li@hbs.edu..
        /// </summary>
        public static string Survey_SurveyComplete_CompleteSubHeader
        {
            get
            {
                return ResourceManager.GetString("Survey_SurveyComplete_CompleteSubHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network Assessment Surveys.
        /// </summary>
        public static string SurveyDashBoard_SurveyCount
        {
            get
            {
                return ResourceManager.GetString("SurveyDashBoard_SurveyCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string SurveyDashBoard_SurveyLink
        {
            get
            {
                return ResourceManager.GetString("SurveyDashBoard_SurveyLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Self Surveys.
        /// </summary>
        public static string SurveyParticipantDashboard_Header
        {
            get
            {
                return ResourceManager.GetString("SurveyParticipantDashboard_Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Action_Cancel
        {
            get
            {
                return ResourceManager.GetString("View_Action_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string View_Actions_Alert
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Alert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string View_Actions_Cancel
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string View_Actions_Label
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string View_Actions_Logout
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string View_Actions_Next
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string View_Actions_PageSetAll
        {
            get
            {
                return ResourceManager.GetString("View_Actions_PageSetAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string View_Actions_Previous
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Previous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string View_Actions_Required
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string View_Actions_Results
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Results", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Results Per Page.
        /// </summary>
        public static string View_Actions_ResultsPerPage
        {
            get
            {
                return ResourceManager.GetString("View_Actions_ResultsPerPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bad Search Term.
        /// </summary>
        public static string View_Actions_SearchError
        {
            get
            {
                return ResourceManager.GetString("View_Actions_SearchError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string View_Actions_Submit
        {
            get
            {
                return ResourceManager.GetString("View_Actions_Submit", resourceCulture);
            }
        }
    }
}
