//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Web.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Web
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Web()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPI.Platform.Web.Properties.Resources.Web", typeof(Resources_Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to zCode.
        /// </summary>
        public static string Account_Code
        {
            get
            {
                return ResourceManager.GetString("Account_Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Account_Code_Error
        {
            get
            {
                return ResourceManager.GetString("Account_Code_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Account_ConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("Account_ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email
        {
            get
            {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Account_Email_Error
        {
            get
            {
                return ResourceManager.GetString("Account_Email_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Account_Id
        {
            get
            {
                return ResourceManager.GetString("Account_Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ../Content/images/leadership_intitiative_horiz_shield_4C_800px.jpg.
        /// </summary>
        public static string Account_Login_Img
        {
            get
            {
                return ResourceManager.GetString("Account_Login_Img", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Account_login_logo
        {
            get
            {
                object obj = ResourceManager.GetObject("Account_login_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UserName Or Password Is Incorrect.
        /// </summary>
        public static string Account_Login_SignInError
        {
            get
            {
                return ResourceManager.GetString("Account_Login_SignInError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Account_Login_Submit
        {
            get
            {
                return ResourceManager.GetString("Account_Login_Submit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please Sign In.
        /// </summary>
        public static string Account_Login_Title
        {
            get
            {
                return ResourceManager.GetString("Account_Login_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Password
        {
            get
            {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Account_PasswordCompareError
        {
            get
            {
                return ResourceManager.GetString("Account_PasswordCompareError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Account_Provider_Error
        {
            get
            {
                return ResourceManager.GetString("Account_Provider_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to zRemeber This Browser ?.
        /// </summary>
        public static string Account_RememberBrowser
        {
            get
            {
                return ResourceManager.GetString("Account_RememberBrowser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Account_RememberMe
        {
            get
            {
                return ResourceManager.GetString("Account_RememberMe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Account_Role
        {
            get
            {
                return ResourceManager.GetString("Account_Role", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Account_Role_Error
        {
            get
            {
                return ResourceManager.GetString("Account_Role_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string Account_StringLengthError
        {
            get
            {
                return ResourceManager.GetString("Account_StringLengthError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to zAdmin.
        /// </summary>
        public static string Group_Administrator
        {
            get
            {
                return ResourceManager.GetString("Group_Administrator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Group_EmailAddress
        {
            get
            {
                return ResourceManager.GetString("Group_EmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Group_EndDate
        {
            get
            {
                return ResourceManager.GetString("Group_EndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to zId.
        /// </summary>
        public static string Group_Id
        {
            get
            {
                return ResourceManager.GetString("Group_Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Group_Name
        {
            get
            {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Group_StartDate
        {
            get
            {
                return ResourceManager.GetString("Group_StartDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Home_Index_MenuTitle
        {
            get
            {
                return ResourceManager.GetString("Home_Index_MenuTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Harvard Business School.
        /// </summary>
        public static string Layout_BrandName
        {
            get
            {
                return ResourceManager.GetString("Layout_BrandName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ../Content/images/Layout_Logo.png.
        /// </summary>
        public static string Layout_Img
        {
            get
            {
                return ResourceManager.GetString("Layout_Img", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Layout_Logo
        {
            get
            {
                object obj = ResourceManager.GetObject("Layout_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Logout
        {
            get
            {
                return ResourceManager.GetString("Layout_Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Layout_Settings
        {
            get
            {
                return ResourceManager.GetString("Layout_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string Layout_ToggleNavigation
        {
            get
            {
                return ResourceManager.GetString("Layout_ToggleNavigation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap old_Account_login_logo
        {
            get
            {
                object obj = ResourceManager.GetObject("old_Account_login_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap old_Layout_Logo
        {
            get
            {
                object obj = ResourceManager.GetObject("old_Layout_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string RegisteredPlugin_Index_MenuTitle
        {
            get
            {
                return ResourceManager.GetString("RegisteredPlugin_Index_MenuTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Registered Plugins.
        /// </summary>
        public static string RegisteredPlugin_Index_Title
        {
            get
            {
                return ResourceManager.GetString("RegisteredPlugin_Index_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admininstrator.
        /// </summary>
        public static string Roles_Admin
        {
            get
            {
                return ResourceManager.GetString("Roles_Admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Program Admin.
        /// </summary>
        public static string Roles_GroupAdmin
        {
            get
            {
                return ResourceManager.GetString("Roles_GroupAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string Roles_Participant
        {
            get
            {
                return ResourceManager.GetString("Roles_Participant", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rater.
        /// </summary>
        public static string Roles_Rater
        {
            get
            {
                return ResourceManager.GetString("Roles_Rater", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Site Admin.
        /// </summary>
        public static string Roles_SiteAdmin
        {
            get
            {
                return ResourceManager.GetString("Roles_SiteAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Super Admin.
        /// </summary>
        public static string Roles_SuperAdmin
        {
            get
            {
                return ResourceManager.GetString("Roles_SuperAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System IT.
        /// </summary>
        public static string Roles_SystemIT
        {
            get
            {
                return ResourceManager.GetString("Roles_SystemIT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Text And/Or Section Is invalid to perform the requested action Please Check the Values and Try Again.
        /// </summary>
        public static string Setup_Encryp_Decrypt_Error
        {
            get
            {
                return ResourceManager.GetString("Setup_Encryp_Decrypt_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup_Index_MenuTitle
        {
            get
            {
                return ResourceManager.GetString("Setup_Index_MenuTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string View_Actions_PageSetAll
        {
            get
            {
                return ResourceManager.GetString("View_Actions_PageSetAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Results Per Page.
        /// </summary>
        public static string View_Actions_ResultsPerPage
        {
            get
            {
                return ResourceManager.GetString("View_Actions_ResultsPerPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string View_Partial_ValidationSummaryError
        {
            get
            {
                return ResourceManager.GetString("View_Partial_ValidationSummaryError", resourceCulture);
            }
        }
    }
}
