//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Entities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPI.Platform.Core.Properties.Resources.Entities", typeof(Resources_Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Dashboard_Id {
            get {
                return ResourceManager.GetString("Dashboard_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Dashboard_Id_Error {
            get {
                return ResourceManager.GetString("Dashboard_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zPartialViewName.
        /// </summary>
        public static string Dashboard_PartialViewName {
            get {
                return ResourceManager.GetString("Dashboard_PartialViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Dashboard_PartialViewName_Error {
            get {
                return ResourceManager.GetString("Dashboard_PartialViewName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zRegisteredPluginsId.
        /// </summary>
        public static string Dashboard_RegisteredPluginsId {
            get {
                return ResourceManager.GetString("Dashboard_RegisteredPluginsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Dashboard_RegisteredPluginsId_Error {
            get {
                return ResourceManager.GetString("Dashboard_RegisteredPluginsId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Dashboard_Role {
            get {
                return ResourceManager.GetString("Dashboard_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        public static string Email_Closing {
            get {
                return ResourceManager.GetString("Email_Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Email_Closing_Error {
            get {
                return ResourceManager.GetString("Email_Closing_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Email_DefaultFrom {
            get {
                return ResourceManager.GetString("Email_DefaultFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required not a valid email address format.
        /// </summary>
        public static string Email_DefaultFrom_EmailAddressError {
            get {
                return ResourceManager.GetString("Email_DefaultFrom_EmailAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Email_DefaultFrom_Error {
            get {
                return ResourceManager.GetString("Email_DefaultFrom_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zvId.
        /// </summary>
        public static string Email_EmailGenericTypeValueId {
            get {
                return ResourceManager.GetString("Email_EmailGenericTypeValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Email_EmailGenericTypeValueId_Error {
            get {
                return ResourceManager.GetString("Email_EmailGenericTypeValueId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zEmail Id.
        /// </summary>
        public static string Email_Id {
            get {
                return ResourceManager.GetString("Email_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Email_Id_Error {
            get {
                return ResourceManager.GetString("Email_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Email_Introduction {
            get {
                return ResourceManager.GetString("Email_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Email_Introduction_Error {
            get {
                return ResourceManager.GetString("Email_Introduction_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Email_Subject {
            get {
                return ResourceManager.GetString("Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Email_Subject_Error {
            get {
                return ResourceManager.GetString("Email_Subject_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Email_Template {
            get {
                return ResourceManager.GetString("Email_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Email_Template_Error {
            get {
                return ResourceManager.GetString("Email_Template_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zTemplate Name.
        /// </summary>
        public static string Email_TemplateName {
            get {
                return ResourceManager.GetString("Email_TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Group_Administrator {
            get {
                return ResourceManager.GetString("Group_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Group_Administrator_Error {
            get {
                return ResourceManager.GetString("Group_Administrator_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string Group_CreateDate {
            get {
                return ResourceManager.GetString("Group_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string Group_CreatedBy {
            get {
                return ResourceManager.GetString("Group_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Group_CreatedBy_Error {
            get {
                return ResourceManager.GetString("Group_CreatedBy_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants Default Password.
        /// </summary>
        public static string Group_DefaultPassword {
            get {
                return ResourceManager.GetString("Group_DefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Group_DefaultPassword_Error {
            get {
                return ResourceManager.GetString("Group_DefaultPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Must have AtLeast:  Total of 6 Characters &lt;br&gt;
        /// 1 Numeric (0 through 9) &lt;br&gt;
        /// 1 English uppercase character (A through Z) &lt;br&gt;
        /// 1 English lowercase characters (a through z) &lt;br&gt;
        /// 1 Non-alphabetic characters (such as !, $, #, %) &lt;br&gt;
        ///Ex.  hbs@Sur1.
        /// </summary>
        public static string Group_DefaultPassword_RegExError {
            get {
                return ResourceManager.GetString("Group_DefaultPassword_RegExError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Group_EmailAddress {
            get {
                return ResourceManager.GetString("Group_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Group_EmailAddress_Error {
            get {
                return ResourceManager.GetString("Group_EmailAddress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Group_EndDate {
            get {
                return ResourceManager.GetString("Group_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Group_EndDate_Error {
            get {
                return ResourceManager.GetString("Group_EndDate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Group_Id {
            get {
                return ResourceManager.GetString("Group_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Group_Id_Error {
            get {
                return ResourceManager.GetString("Group_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Group_Name_Error {
            get {
                return ResourceManager.GetString("Group_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zProgram Id.
        /// </summary>
        public static string Group_ProgramId {
            get {
                return ResourceManager.GetString("Group_ProgramId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Group_StartDate {
            get {
                return ResourceManager.GetString("Group_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Group_StartDate_Error {
            get {
                return ResourceManager.GetString("Group_StartDate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Group_StatusGenericTypeId {
            get {
                return ResourceManager.GetString("Group_StatusGenericTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Group_TypeGenericTypeId {
            get {
                return ResourceManager.GetString("Group_TypeGenericTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zGroup Email Email Id.
        /// </summary>
        public static string GroupEmail_EmailId {
            get {
                return ResourceManager.GetString("GroupEmail_EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string GroupEmail_EmailId_Error {
            get {
                return ResourceManager.GetString("GroupEmail_EmailId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zGroup Email Group Id.
        /// </summary>
        public static string GroupEmail_GroupId {
            get {
                return ResourceManager.GetString("GroupEmail_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string GroupEmail_GroupId_Error {
            get {
                return ResourceManager.GetString("GroupEmail_GroupId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zGroup Email Id.
        /// </summary>
        public static string GroupEmail_Id {
            get {
                return ResourceManager.GetString("GroupEmail_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string GroupEmail_Id_Error {
            get {
                return ResourceManager.GetString("GroupEmail_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Date.
        /// </summary>
        public static string GroupParticipant_AddedDate {
            get {
                return ResourceManager.GetString("GroupParticipant_AddedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string GroupParticipant_AddedDate_Error {
            get {
                return ResourceManager.GetString("GroupParticipant_AddedDate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        public static string GroupParticipant_GroupId {
            get {
                return ResourceManager.GetString("GroupParticipant_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string GroupParticipant_GroupId_Error {
            get {
                return ResourceManager.GetString("GroupParticipant_GroupId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string GroupParticipant_Id {
            get {
                return ResourceManager.GetString("GroupParticipant_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string GroupParticipant_Id_Error {
            get {
                return ResourceManager.GetString("GroupParticipant_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string GroupParticipant_ParticipantId {
            get {
                return ResourceManager.GetString("GroupParticipant_ParticipantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string GroupParticipant_ParticipantId_Error {
            get {
                return ResourceManager.GetString("GroupParticipant_ParticipantId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Participant_Id {
            get {
                return ResourceManager.GetString("Participant_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is Deleted.
        /// </summary>
        public static string Participant_IsDeleted {
            get {
                return ResourceManager.GetString("Participant_IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Participant_IsDeleted_Error {
            get {
                return ResourceManager.GetString("Participant_IsDeleted_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Id.
        /// </summary>
        public static string Participant_PersonId {
            get {
                return ResourceManager.GetString("Participant_PersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?=(.*\d){1})(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z\d]).{6,}$.
        /// </summary>
        public static string PasswordValidationRegex {
            get {
                return ResourceManager.GetString("PasswordValidationRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id.
        /// </summary>
        public static string Person_AspNetUsersId {
            get {
                return ResourceManager.GetString("Person_AspNetUsersId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Person_AspNetUsersId_Error {
            get {
                return ResourceManager.GetString("Person_AspNetUsersId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Person_Email {
            get {
                return ResourceManager.GetString("Person_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Person_Email_Error {
            get {
                return ResourceManager.GetString("Person_Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Person_First_Name {
            get {
                return ResourceManager.GetString("Person_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Person_First_Name_Error {
            get {
                return ResourceManager.GetString("Person_First_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zId.
        /// </summary>
        public static string Person_Id {
            get {
                return ResourceManager.GetString("Person_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Person_Id_Error {
            get {
                return ResourceManager.GetString("Person_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Person_Last_Name {
            get {
                return ResourceManager.GetString("Person_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Person_Last_Name_Error {
            get {
                return ResourceManager.GetString("Person_Last_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zMiddle Name.
        /// </summary>
        public static string Person_Middle_Name {
            get {
                return ResourceManager.GetString("Person_Middle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zPrefix.
        /// </summary>
        public static string Person_Prefix {
            get {
                return ResourceManager.GetString("Person_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zSuffix.
        /// </summary>
        public static string Person_Suffix {
            get {
                return ResourceManager.GetString("Person_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string PersonGroupEmail_Body {
            get {
                return ResourceManager.GetString("PersonGroupEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string PersonGroupEmail_ErrorMessage {
            get {
                return ResourceManager.GetString("PersonGroupEmail_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string PersonGroupEmail_GroupEmailId {
            get {
                return ResourceManager.GetString("PersonGroupEmail_GroupEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string PersonGroupEmail_GroupEmailId_Error {
            get {
                return ResourceManager.GetString("PersonGroupEmail_GroupEmailId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string PersonGroupEmail_Id {
            get {
                return ResourceManager.GetString("PersonGroupEmail_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string PersonGroupEmail_Id_Error {
            get {
                return ResourceManager.GetString("PersonGroupEmail_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string PersonGroupEmail_OrginalToAddress {
            get {
                return ResourceManager.GetString("PersonGroupEmail_OrginalToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string PersonGroupEmail_PersonId {
            get {
                return ResourceManager.GetString("PersonGroupEmail_PersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string PersonGroupEmail_PersonId_Error {
            get {
                return ResourceManager.GetString("PersonGroupEmail_PersonId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string PersonGroupEmail_RetryCount {
            get {
                return ResourceManager.GetString("PersonGroupEmail_RetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Email Date.
        /// </summary>
        public static string PersonGroupEmail_SendDate {
            get {
                return ResourceManager.GetString("PersonGroupEmail_SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a date format MM/DD/YY.
        /// </summary>
        public static string PersonGroupEmail_SendDate_Error {
            get {
                return ResourceManager.GetString("PersonGroupEmail_SendDate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string PersonGroupEmail_SendStatusGenericTypeValueId {
            get {
                return ResourceManager.GetString("PersonGroupEmail_SendStatusGenericTypeValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Plugin ?.
        /// </summary>
        public static string RegisteredPlugin_Custom {
            get {
                return ResourceManager.GetString("RegisteredPlugin_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RegisteredPlugin_Description {
            get {
                return ResourceManager.GetString("RegisteredPlugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path.
        /// </summary>
        public static string RegisteredPlugin_FullPath {
            get {
                return ResourceManager.GetString("RegisteredPlugin_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string RegisteredPlugin_FullPath_Error {
            get {
                return ResourceManager.GetString("RegisteredPlugin_FullPath_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zId.
        /// </summary>
        public static string RegisteredPlugin_Id {
            get {
                return ResourceManager.GetString("RegisteredPlugin_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string RegisteredPlugin_Id_Error {
            get {
                return ResourceManager.GetString("RegisteredPlugin_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Date.
        /// </summary>
        public static string RegisteredPlugin_InstallationDate {
            get {
                return ResourceManager.GetString("RegisteredPlugin_InstallationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string RegisteredPlugin_Name {
            get {
                return ResourceManager.GetString("RegisteredPlugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string RegisteredPlugin_Name_Error {
            get {
                return ResourceManager.GetString("RegisteredPlugin_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string RegisteredPlugin_Version {
            get {
                return ResourceManager.GetString("RegisteredPlugin_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zzID.
        /// </summary>
        public static string Survey_Id {
            get {
                return ResourceManager.GetString("Survey_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Survey_Id_Error {
            get {
                return ResourceManager.GetString("Survey_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Name.
        /// </summary>
        public static string Survey_Name {
            get {
                return ResourceManager.GetString("Survey_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string Survey_Name_Error {
            get {
                return ResourceManager.GetString("Survey_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string SurveyGroupParticipant_GroupParticipantId {
            get {
                return ResourceManager.GetString("SurveyGroupParticipant_GroupParticipantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string SurveyGroupParticipant_Id {
            get {
                return ResourceManager.GetString("SurveyGroupParticipant_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string SurveyGroupParticipant_Id_Error {
            get {
                return ResourceManager.GetString("SurveyGroupParticipant_Id_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string SurveyGroupParticipant_ParticipantId_Error {
            get {
                return ResourceManager.GetString("SurveyGroupParticipant_ParticipantId_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SurveyGroupParticipant_StatusGenericTypeValueId {
            get {
                return ResourceManager.GetString("SurveyGroupParticipant_StatusGenericTypeValueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zz.
        /// </summary>
        public static string SurveyGroupParticipant_SurveyId {
            get {
                return ResourceManager.GetString("SurveyGroupParticipant_SurveyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Required.
        /// </summary>
        public static string SurveyGroupParticipant_SurveyId_Error {
            get {
                return ResourceManager.GetString("SurveyGroupParticipant_SurveyId_Error", resourceCulture);
            }
        }
    }
}
