//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(AspNetUserMetadata))]
	public partial class AspNetUser
	{
		internal sealed class AspNetUserMetadata
		{
		
			[Required(ErrorMessageResourceName="AspNetUser_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(128)]
    		[Display(Name = "AspNetUser_Id",ResourceType=typeof(Resources_Entities))]
			public String Id { get; set; }

			[StringLength(256)]
			[DataType(DataType.EmailAddress)]
    		[Display(Name = "AspNetUser_Email",ResourceType=typeof(Resources_Entities))]
			public String Email { get; set; }

			[Required(ErrorMessageResourceName="AspNetUser_EmailConfirmed_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.EmailAddress)]
    		[Display(Name = "AspNetUser_EmailConfirmed",ResourceType=typeof(Resources_Entities))]
			public Boolean EmailConfirmed { get; set; }

    		[Display(Name = "AspNetUser_PasswordHash",ResourceType=typeof(Resources_Entities))]
			public String PasswordHash { get; set; }

    		[Display(Name = "AspNetUser_SecurityStamp",ResourceType=typeof(Resources_Entities))]
			public String SecurityStamp { get; set; }

			[DataType(DataType.PhoneNumber)]
    		[Display(Name = "AspNetUser_PhoneNumber",ResourceType=typeof(Resources_Entities))]
			public String PhoneNumber { get; set; }

			[Required(ErrorMessageResourceName="AspNetUser_PhoneNumberConfirmed_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.PhoneNumber)]
    		[Display(Name = "AspNetUser_PhoneNumberConfirmed",ResourceType=typeof(Resources_Entities))]
			public Boolean PhoneNumberConfirmed { get; set; }

			[Required(ErrorMessageResourceName="AspNetUser_TwoFactorEnabled_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "AspNetUser_TwoFactorEnabled",ResourceType=typeof(Resources_Entities))]
			public Boolean TwoFactorEnabled { get; set; }

			[DataType(DataType.DateTime)]
    		[Display(Name = "AspNetUser_LockoutEndDateUtc",ResourceType=typeof(Resources_Entities))]
			public DateTime LockoutEndDateUtc { get; set; }

			[Required(ErrorMessageResourceName="AspNetUser_LockoutEnabled_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "AspNetUser_LockoutEnabled",ResourceType=typeof(Resources_Entities))]
			public Boolean LockoutEnabled { get; set; }

			[Required(ErrorMessageResourceName="AspNetUser_AccessFailedCount_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "AspNetUser_AccessFailedCount",ResourceType=typeof(Resources_Entities))]
			public Int32 AccessFailedCount { get; set; }

			[Required(ErrorMessageResourceName="AspNetUser_UserName_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(256)]
    		[Display(Name = "AspNetUser_UserName",ResourceType=typeof(Resources_Entities))]
			public String UserName { get; set; }

		}
	}
}
	
