//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(CultureMetadata))]
	public partial class Culture
	{
		internal sealed class CultureMetadata
		{
		
			[Required(ErrorMessageResourceName="Culture_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "Culture_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="Culture_Value_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(50)]
    		[Display(Name = "Culture_Value",ResourceType=typeof(Resources_Entities))]
			public String Value { get; set; }

    		//public EntityCollection<ResourceValue> ResourceValues { get; set; }

		}
	}
}
	
