//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class Email
    {
        public Email()
        {
            this.GroupEmails = new HashSet<GroupEmail>();
        }
    
        public int Id { get; set; }
        public int EmailGenericTypeValueId { get; set; }
        public string DefaultFrom { get; set; }
        public string Subject { get; set; }
        public string Introduction { get; set; }
        public string Closing { get; set; }
        public bool Template { get; set; }
        public string TemplateName { get; set; }
    
        public virtual GenericTypeValue EmailGenericTypeValue { get; set; }
        public virtual ICollection<GroupEmail> GroupEmails { get; set; }
    }
}
