//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class GenericTypeValue
    {
        public GenericTypeValue()
        {
            this.Emails = new HashSet<Email>();
            this.PersonGroupEmails = new HashSet<PersonGroupEmail>();
            this.PluginActions = new HashSet<PluginAction>();
            this.Groups = new HashSet<Group>();
            this.Groups1 = new HashSet<Group>();
            this.SurveyGroupParticipants = new HashSet<SurveyGroupParticipant>();
        }
    
        public int Id { get; set; }
        public int GenericTypeId { get; set; }
        public int ResourceId { get; set; }
    
        public virtual ICollection<Email> Emails { get; set; }
        public virtual GenericType GenericType { get; set; }
        public virtual ICollection<PersonGroupEmail> PersonGroupEmails { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ICollection<PluginAction> PluginActions { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Group> Groups1 { get; set; }
        public virtual ICollection<SurveyGroupParticipant> SurveyGroupParticipants { get; set; }
    }
}
