//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(GenericTypeMetadata))]
	public partial class GenericType
	{
		internal sealed class GenericTypeMetadata
		{
		
			[Required(ErrorMessageResourceName="GenericType_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GenericType_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="GenericType_Name_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(150)]
    		[Display(Name = "GenericType_Name",ResourceType=typeof(Resources_Entities))]
			public String Name { get; set; }

    		//public EntityCollection<GenericTypeValue> GenericTypeValues { get; set; }

		}
	}
}
	
