//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(GenericTypeValueMetadata))]
	public partial class GenericTypeValue
	{
		internal sealed class GenericTypeValueMetadata
		{
		
			[Required(ErrorMessageResourceName="GenericTypeValue_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GenericTypeValue_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="GenericTypeValue_GenericTypeId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GenericTypeValue_GenericTypeId",ResourceType=typeof(Resources_Entities))]
			public Int32 GenericTypeId { get; set; }

			[Required(ErrorMessageResourceName="GenericTypeValue_ResourceId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GenericTypeValue_ResourceId",ResourceType=typeof(Resources_Entities))]
			public Int32 ResourceId { get; set; }

    		//public EntityCollection<Email> Emails { get; set; }

    		//public EntityCollection<GenericType> GenericType { get; set; }

    		//public EntityCollection<PersonGroupEmail> PersonGroupEmails { get; set; }

    		//public EntityCollection<Resource> Resource { get; set; }

    		//public EntityCollection<PluginAction> PluginActions { get; set; }

    		//public EntityCollection<Group> Groups { get; set; }

    		//public EntityCollection<Group> Groups1 { get; set; }

    		//public EntityCollection<SurveyGroupParticipant> SurveyGroupParticipants { get; set; }

		}
	}
}
	
