//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(GroupMetadata))]
	public partial class Group
	{
		internal sealed class GroupMetadata
		{
		
			[Required(ErrorMessageResourceName="Group_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "Group_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

    		[Display(Name = "Group_ProgramId",ResourceType=typeof(Resources_Entities))]
			public Int32 ProgramId { get; set; }

			[Required(ErrorMessageResourceName="Group_Name_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(150)]
    		[Display(Name = "Group_Name",ResourceType=typeof(Resources_Entities))]
			public String Name { get; set; }

			[Required(ErrorMessageResourceName="Group_Administrator_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(250)]
    		[Display(Name = "Group_Administrator",ResourceType=typeof(Resources_Entities))]
			public String Administrator { get; set; }

			[Required(ErrorMessageResourceName="Group_EmailAddress_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(250)]
			[DataType(DataType.EmailAddress)]
    		[Display(Name = "Group_EmailAddress",ResourceType=typeof(Resources_Entities))]
			public String EmailAddress { get; set; }

			[Required(ErrorMessageResourceName="Group_StartDate_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.DateTime)]
    		[Display(Name = "Group_StartDate",ResourceType=typeof(Resources_Entities))]
			public DateTime StartDate { get; set; }

			[Required(ErrorMessageResourceName="Group_EndDate_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.DateTime)]
    		[Display(Name = "Group_EndDate",ResourceType=typeof(Resources_Entities))]
			public DateTime EndDate { get; set; }

			[DataType(DataType.DateTime)]
    		[Display(Name = "Group_CreateDate",ResourceType=typeof(Resources_Entities))]
			public DateTime CreateDate { get; set; }

    		[Display(Name = "Group_StatusGenericTypeValueId",ResourceType=typeof(Resources_Entities))]
			public Int32 StatusGenericTypeValueId { get; set; }

    		[Display(Name = "Group_TypeGenericTypeValueId",ResourceType=typeof(Resources_Entities))]
			public Int32 TypeGenericTypeValueId { get; set; }

			[Required(ErrorMessageResourceName="Group_CreatedBy_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(50)]
    		[Display(Name = "Group_CreatedBy",ResourceType=typeof(Resources_Entities))]
			public String CreatedBy { get; set; }

    		//public EntityCollection<GenericTypeValue> StatusGenericTypeValue { get; set; }

    		//public EntityCollection<GenericTypeValue> TypeGenericTypeValue1 { get; set; }

    		//public EntityCollection<Program> Program { get; set; }

    		//public EntityCollection<GroupEmail> GroupEmails { get; set; }

    		//public EntityCollection<GroupParticipant> GroupParticipants { get; set; }

		}
	}
}
	
