//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class GroupParticipant
    {
        public GroupParticipant()
        {
            this.SurveyGroupParticipants = new HashSet<SurveyGroupParticipant>();
        }
    
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int ParticipantId { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual ICollection<SurveyGroupParticipant> SurveyGroupParticipants { get; set; }
    }
}
