//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(GroupEmailMetadata))]
	public partial class GroupEmail
	{
		internal sealed class GroupEmailMetadata
		{
		
			[Required(ErrorMessageResourceName="GroupEmail_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GroupEmail_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="GroupEmail_GroupId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GroupEmail_GroupId",ResourceType=typeof(Resources_Entities))]
			public Int32 GroupId { get; set; }

			[Required(ErrorMessageResourceName="GroupEmail_EmailId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.EmailAddress)]
    		[Display(Name = "GroupEmail_EmailId",ResourceType=typeof(Resources_Entities))]
			public Int32 EmailId { get; set; }

    		//public EntityCollection<Email> Email { get; set; }

    		//public EntityCollection<Group> Group { get; set; }

    		//public EntityCollection<PersonGroupEmail> PersonGroupEmails { get; set; }

		}
	}
}
	
