//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(GroupParticipantMetadata))]
	public partial class GroupParticipant
	{
		internal sealed class GroupParticipantMetadata
		{
		
			[Required(ErrorMessageResourceName="GroupParticipant_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GroupParticipant_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="GroupParticipant_GroupId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GroupParticipant_GroupId",ResourceType=typeof(Resources_Entities))]
			public Int32 GroupId { get; set; }

			[Required(ErrorMessageResourceName="GroupParticipant_ParticipantId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "GroupParticipant_ParticipantId",ResourceType=typeof(Resources_Entities))]
			public Int32 ParticipantId { get; set; }

			[Required(ErrorMessageResourceName="GroupParticipant_AddedDate_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.DateTime)]
    		[Display(Name = "GroupParticipant_AddedDate",ResourceType=typeof(Resources_Entities))]
			public DateTime AddedDate { get; set; }

    		//public EntityCollection<Group> Group { get; set; }

    		//public EntityCollection<Participant> Participant { get; set; }

    		//public EntityCollection<SurveyGroupParticipant> SurveyGroupParticipants { get; set; }

		}
	}
}
	
