//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class Group
    {
        public Group()
        {
            this.GroupEmails = new HashSet<GroupEmail>();
            this.GroupParticipants = new HashSet<GroupParticipant>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string Name { get; set; }
        public string Administrator { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> StatusGenericTypeValueId { get; set; }
        public Nullable<int> TypeGenericTypeValueId { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual GenericTypeValue StatusGenericTypeValue { get; set; }
        public virtual GenericTypeValue TypeGenericTypeValue1 { get; set; }
        public virtual Program Program { get; set; }
        public virtual ICollection<GroupEmail> GroupEmails { get; set; }
        public virtual ICollection<GroupParticipant> GroupParticipants { get; set; }
    }
}
