//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(ParticipantMetadata))]
	public partial class Participant
	{
		internal sealed class ParticipantMetadata
		{
		
			[Required(ErrorMessageResourceName="Participant_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "Participant_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="Participant_PersonId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "Participant_PersonId",ResourceType=typeof(Resources_Entities))]
			public Int32 PersonId { get; set; }

    		//public EntityCollection<GroupParticipant> GroupParticipants { get; set; }

    		//public EntityCollection<Person> Person { get; set; }

		}
	}
}
	
