//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class Participant
    {
        public Participant()
        {
            this.GroupParticipants = new HashSet<GroupParticipant>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
    
        public virtual ICollection<GroupParticipant> GroupParticipants { get; set; }
        public virtual Person Person { get; set; }
    }
}
