//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(PersonGroupEmailMetadata))]
	public partial class PersonGroupEmail
	{
		internal sealed class PersonGroupEmailMetadata
		{
		
			[Required(ErrorMessageResourceName="PersonGroupEmail_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "PersonGroupEmail_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="PersonGroupEmail_PersonId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "PersonGroupEmail_PersonId",ResourceType=typeof(Resources_Entities))]
			public Int32 PersonId { get; set; }

			[Required(ErrorMessageResourceName="PersonGroupEmail_GroupEmailId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.EmailAddress)]
    		[Display(Name = "PersonGroupEmail_GroupEmailId",ResourceType=typeof(Resources_Entities))]
			public Int32 GroupEmailId { get; set; }

			[Required(ErrorMessageResourceName="PersonGroupEmail_SendDate_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.DateTime)]
    		[Display(Name = "PersonGroupEmail_SendDate",ResourceType=typeof(Resources_Entities))]
			public DateTime SendDate { get; set; }

    		[Display(Name = "PersonGroupEmail_SendStatusGenericTypeValueId",ResourceType=typeof(Resources_Entities))]
			public Int32 SendStatusGenericTypeValueId { get; set; }

			[StringLength(250)]
    		[Display(Name = "PersonGroupEmail_OrginalToAddress",ResourceType=typeof(Resources_Entities))]
			public String OrginalToAddress { get; set; }

    		[Display(Name = "PersonGroupEmail_Body",ResourceType=typeof(Resources_Entities))]
			public String Body { get; set; }

    		[Display(Name = "PersonGroupEmail_RetryCount",ResourceType=typeof(Resources_Entities))]
			public Int32 RetryCount { get; set; }

			[StringLength(500)]
    		[Display(Name = "PersonGroupEmail_ErrorMessage",ResourceType=typeof(Resources_Entities))]
			public String ErrorMessage { get; set; }

    		//public EntityCollection<GenericTypeValue> SendGenericTypeValue { get; set; }

    		//public EntityCollection<GroupEmail> GroupEmail { get; set; }

    		//public EntityCollection<Person> Person { get; set; }

		}
	}
}
	
