//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(PersonMetadata))]
	public partial class Person
	{
		internal sealed class PersonMetadata
		{
		
			[Required(ErrorMessageResourceName="Person_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "Person_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[StringLength(50)]
    		[Display(Name = "Person_Prefix",ResourceType=typeof(Resources_Entities))]
			public String Prefix { get; set; }

			[Required(ErrorMessageResourceName="Person_First_Name_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(150)]
    		[Display(Name = "Person_First_Name",ResourceType=typeof(Resources_Entities))]
			public String First_Name { get; set; }

			[Required(ErrorMessageResourceName="Person_Last_Name_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(150)]
    		[Display(Name = "Person_Last_Name",ResourceType=typeof(Resources_Entities))]
			public String Last_Name { get; set; }

			[StringLength(150)]
    		[Display(Name = "Person_Middle_Name",ResourceType=typeof(Resources_Entities))]
			public String Middle_Name { get; set; }

			[StringLength(50)]
    		[Display(Name = "Person_Suffix",ResourceType=typeof(Resources_Entities))]
			public String Suffix { get; set; }

			[Required(ErrorMessageResourceName="Person_Email_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(250)]
			[DataType(DataType.EmailAddress)]
    		[Display(Name = "Person_Email",ResourceType=typeof(Resources_Entities))]
			public String Email { get; set; }

			[StringLength(50)]
    		[Display(Name = "Person_AspNetUsersId",ResourceType=typeof(Resources_Entities))]
			public String AspNetUsersId { get; set; }

    		//public EntityCollection<Participant> Participants { get; set; }

    		//public EntityCollection<PersonGroupEmail> PersonGroupEmails { get; set; }

    		//public EntityCollection<Rater> Raters { get; set; }

		}
	}
}
	
