//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlatformEntities : DbContext
    {
        public PlatformEntities()
            : base("name=PlatformEntities")
        {
    		((IObjectContextAdapter)this).ObjectContext.ObjectMaterialized += new ObjectMaterializedEventHandler(ObjectMaterialized);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Culture> Cultures { get; set; }
        public virtual DbSet<Dashboard> Dashboards { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<GenericType> GenericTypes { get; set; }
        public virtual DbSet<GenericTypeValue> GenericTypeValues { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupEmail> GroupEmails { get; set; }
        public virtual DbSet<GroupParticipant> GroupParticipants { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonGroupEmail> PersonGroupEmails { get; set; }
        public virtual DbSet<PluginAction> PluginActions { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Rater> Raters { get; set; }
        public virtual DbSet<RegisteredPlugin> RegisteredPlugins { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ResourceValue> ResourceValues { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SurveyGroupParticipant> SurveyGroupParticipants { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
