//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(PluginActionMetadata))]
	public partial class PluginAction
	{
		internal sealed class PluginActionMetadata
		{
		
			[Required(ErrorMessageResourceName="PluginAction_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "PluginAction_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="PluginAction_RegisteredPluginsId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "PluginAction_RegisteredPluginsId",ResourceType=typeof(Resources_Entities))]
			public Int32 RegisteredPluginsId { get; set; }

			[Required(ErrorMessageResourceName="PluginAction_ForView_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(150)]
    		[Display(Name = "PluginAction_ForView",ResourceType=typeof(Resources_Entities))]
			public String ForView { get; set; }

			[Required(ErrorMessageResourceName="PluginAction_ActionGenericTypeIValueId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "PluginAction_ActionGenericTypeIValueId",ResourceType=typeof(Resources_Entities))]
			public Int32 ActionGenericTypeIValueId { get; set; }

			[Required(ErrorMessageResourceName="PluginAction_Action_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(50)]
    		[Display(Name = "PluginAction_Action",ResourceType=typeof(Resources_Entities))]
			public String Action { get; set; }

			[Required(ErrorMessageResourceName="PluginAction_Controller_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(50)]
    		[Display(Name = "PluginAction_Controller",ResourceType=typeof(Resources_Entities))]
			public String Controller { get; set; }

    		[Display(Name = "PluginAction_RoutingData",ResourceType=typeof(Resources_Entities))]
			public String RoutingData { get; set; }

    		//public EntityCollection<GenericTypeValue> ActionGenericTypeValue { get; set; }

    		//public EntityCollection<RegisteredPlugin> RegisteredPlugin { get; set; }

		}
	}
}
	
