//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(ProgramMetadata))]
	public partial class Program
	{
		internal sealed class ProgramMetadata
		{
		
			[Required(ErrorMessageResourceName="Program_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "Program_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="Program_SiteId_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "Program_SiteId",ResourceType=typeof(Resources_Entities))]
			public Int32 SiteId { get; set; }

			[Required(ErrorMessageResourceName="Program_Name_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(150)]
    		[Display(Name = "Program_Name",ResourceType=typeof(Resources_Entities))]
			public String Name { get; set; }

    		//public EntityCollection<Group> Groups { get; set; }

    		//public EntityCollection<Site> Site { get; set; }

		}
	}
}
	
