//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(RegisteredPluginMetadata))]
	public partial class RegisteredPlugin
	{
		internal sealed class RegisteredPluginMetadata
		{
		
			[Required(ErrorMessageResourceName="RegisteredPlugin_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "RegisteredPlugin_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="RegisteredPlugin_Name_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(50)]
    		[Display(Name = "RegisteredPlugin_Name",ResourceType=typeof(Resources_Entities))]
			public String Name { get; set; }

			[Required(ErrorMessageResourceName="RegisteredPlugin_Version_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(50)]
    		[Display(Name = "RegisteredPlugin_Version",ResourceType=typeof(Resources_Entities))]
			public String Version { get; set; }

			[Required(ErrorMessageResourceName="RegisteredPlugin_Custom_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "RegisteredPlugin_Custom",ResourceType=typeof(Resources_Entities))]
			public Boolean Custom { get; set; }

			[StringLength(250)]
    		[Display(Name = "RegisteredPlugin_Description",ResourceType=typeof(Resources_Entities))]
			public String Description { get; set; }

			[Required(ErrorMessageResourceName="RegisteredPlugin_InstallationDate_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[DataType(DataType.DateTime)]
    		[Display(Name = "RegisteredPlugin_InstallationDate",ResourceType=typeof(Resources_Entities))]
			public DateTime InstallationDate { get; set; }

			[Required(ErrorMessageResourceName="RegisteredPlugin_FullPath_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(250)]
    		[Display(Name = "RegisteredPlugin_FullPath",ResourceType=typeof(Resources_Entities))]
			public String FullPath { get; set; }

    		//public EntityCollection<Dashboard> Dashboards { get; set; }

    		//public EntityCollection<PluginAction> PluginActions { get; set; }

		}
	}
}
	
