//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class RegisteredPlugin
    {
        public RegisteredPlugin()
        {
            this.Dashboards = new HashSet<Dashboard>();
            this.PluginActions = new HashSet<PluginAction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public bool Custom { get; set; }
        public string Description { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public string FullPath { get; set; }
    
        public virtual ICollection<Dashboard> Dashboards { get; set; }
        public virtual ICollection<PluginAction> PluginActions { get; set; }
    }
}
