//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class Resource
    {
        public Resource()
        {
            this.GenericTypeValues = new HashSet<GenericTypeValue>();
            this.ResourceValues = new HashSet<ResourceValue>();
        }
    
        public int Id { get; set; }
        public string TableName { get; set; }
    
        public virtual ICollection<GenericTypeValue> GenericTypeValues { get; set; }
        public virtual ICollection<ResourceValue> ResourceValues { get; set; }
    }
}
