//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class ResourceValue
    {
        public int Id { get; set; }
        public int ResourceId { get; set; }
        public int CultureId { get; set; }
        public string Value { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
