//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
	  
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using PPI.Platform.Core.Properties;
using PPI.Platform.Core.Attributes;

namespace PPI.Platform.Core.Entities
{

[MetadataType(typeof(SurveyMetadata))]
	public partial class Survey
	{
		internal sealed class SurveyMetadata
		{
		
			[Required(ErrorMessageResourceName="Survey_Id_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
    		[Display(Name = "Survey_Id",ResourceType=typeof(Resources_Entities))]
			public Int32 Id { get; set; }

			[Required(ErrorMessageResourceName="Survey_Name_Error",ErrorMessageResourceType=typeof(Resources_Entities))]			
			[StringLength(250)]
    		[Display(Name = "Survey_Name",ResourceType=typeof(Resources_Entities))]
			public String Name { get; set; }

    		//public EntityCollection<SurveyGroupParticipant> SurveyGroupParticipants { get; set; }

		}
	}
}
	
