//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Platform.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    using PPI.Platform.Core.Attributes;
    public partial class SurveyGroupParticipant
    {
        public int Id { get; set; }
        public int SurveyId { get; set; }
        public int GroupParticipantId { get; set; }
        public Nullable<int> StatusGenericTypeValueId { get; set; }
    
        public virtual GenericTypeValue StatusGenericTypeValue { get; set; }
        public virtual GroupParticipant GroupParticipant { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
