//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Plugin.Administration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Administration_Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Administration_Web() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPI.Plugin.Administration.Properties.Resources.Administration.Web", typeof(Resources_Administration_Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string AdminDashboard_ParticipantCount {
            get {
                return ResourceManager.GetString("AdminDashboard_ParticipantCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string AdminDashboard_ParticipantLink {
            get {
                return ResourceManager.GetString("AdminDashboard_ParticipantLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string AdminDashboard_ProjectCount {
            get {
                return ResourceManager.GetString("AdminDashboard_ProjectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string AdminDashboard_ProjectLink {
            get {
                return ResourceManager.GetString("AdminDashboard_ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Title.
        /// </summary>
        public static string Administartion_Index_Title {
            get {
                return ResourceManager.GetString("Administartion_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Participant.
        /// </summary>
        public static string Participant_Index_AddButton {
            get {
                return ResourceManager.GetString("Participant_Index_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Program --.
        /// </summary>
        public static string Participant_Index_SearchDropDown {
            get {
                return ResourceManager.GetString("Participant_Index_SearchDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participant_Index_Title {
            get {
                return ResourceManager.GetString("Participant_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Participants.
        /// </summary>
        public static string Participant_Index_UploadButton {
            get {
                return ResourceManager.GetString("Participant_Index_UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Programs.
        /// </summary>
        public static string Project_Index_AddButton {
            get {
                return ResourceManager.GetString("Project_Index_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string Project_Index_Title {
            get {
                return ResourceManager.GetString("Project_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string View_Actions_Label {
            get {
                return ResourceManager.GetString("View_Actions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string View_Actions_PageSetAll {
            get {
                return ResourceManager.GetString("View_Actions_PageSetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string View_Actions_Results {
            get {
                return ResourceManager.GetString("View_Actions_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Per Page.
        /// </summary>
        public static string View_Actions_ResultsPerPage {
            get {
                return ResourceManager.GetString("View_Actions_ResultsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Search Term Using No Filter.
        /// </summary>
        public static string View_Actions_SearchError {
            get {
                return ResourceManager.GetString("View_Actions_SearchError", resourceCulture);
            }
        }
    }
}
