//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Plugin.Survey.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkRelationshipDemo
    {
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public int NetworkContactID { get; set; }
        public string ContactName { get; set; }
        public int RelationshipID { get; set; }
        public Nullable<bool> DiffFuncArea { get; set; }
        public Nullable<bool> DiffBsnUnit { get; set; }
        public Nullable<bool> DiffFirm { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<bool> SameNativeLang { get; set; }
        public Nullable<int> AgeGroup { get; set; }
        public int CreaterBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual NetworkInfoContact NetworkInfoContact { get; set; }
    }
}
