//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Plugin.Survey.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkInfoContact
    {
        public NetworkInfoContact()
        {
            this.NetworkRelationships = new HashSet<NetworkRelationship>();
            this.RelationshipDensities = new HashSet<RelationshipDensity>();
            this.ParticipantProfiles = new HashSet<ParticipantProfile>();
            this.NetworkRelationshipDemoes = new HashSet<NetworkRelationshipDemo>();
        }
    
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public string ContactName1 { get; set; }
        public string ContactName2 { get; set; }
        public string ContactName3 { get; set; }
        public string ContactName4 { get; set; }
        public string ContactName5 { get; set; }
        public string ContactName6 { get; set; }
        public string ContactName7 { get; set; }
        public string ContactName8 { get; set; }
        public string JobContactName1 { get; set; }
        public string JobContactName2 { get; set; }
        public string JobContactName3 { get; set; }
        public string JobContactName4 { get; set; }
        public string JobContactName5 { get; set; }
        public string JobContactName6 { get; set; }
        public string JobContactName7 { get; set; }
        public string JobContactName8 { get; set; }
        public string CrrContactName1 { get; set; }
        public string CrrContactName2 { get; set; }
        public string CrrContactName3 { get; set; }
        public string CrrContactName4 { get; set; }
        public string CrrContactName5 { get; set; }
        public string CrrContactName6 { get; set; }
        public string CrrContactName7 { get; set; }
        public string CrrContactName8 { get; set; }
        public int CreaterBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> AllowNewContacts { get; set; }
    
        public virtual ICollection<NetworkRelationship> NetworkRelationships { get; set; }
        public virtual ICollection<RelationshipDensity> RelationshipDensities { get; set; }
        public virtual ICollection<ParticipantProfile> ParticipantProfiles { get; set; }
        public virtual ICollection<NetworkRelationshipDemo> NetworkRelationshipDemoes { get; set; }
    }
}
