//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Plugin.Survey.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantProfile
    {
        public int id { get; set; }
        public int NetworkContactID { get; set; }
        public int ParticipantID { get; set; }
        public Nullable<int> NativeLang { get; set; }
        public int CreaterBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> AgeGroupId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> NetworkPercentId { get; set; }
        public Nullable<int> WorkRegionId { get; set; }
    
        public virtual NetworkInfoContact NetworkInfoContact { get; set; }
    }
}
