//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Plugin.Survey.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationshipDensity
    {
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public int NetworkContactID { get; set; }
        public string ContactName { get; set; }
        public string MapContactName2 { get; set; }
        public string MapContactName3 { get; set; }
        public string MapContactName4 { get; set; }
        public string MapContactName5 { get; set; }
        public string MapContactName6 { get; set; }
        public string MapContactName7 { get; set; }
        public string MapContactName8 { get; set; }
        public string MapContactName9 { get; set; }
        public string MapContactName10 { get; set; }
        public string MapContactName11 { get; set; }
        public string MapContactName12 { get; set; }
        public string MapContactName13 { get; set; }
        public string MapContactName14 { get; set; }
        public string MapContactName15 { get; set; }
        public string MapContactName16 { get; set; }
        public string MapContactName17 { get; set; }
        public string MapContactName18 { get; set; }
        public string MapContactName19 { get; set; }
        public string MapContactName20 { get; set; }
        public string MapContactName21 { get; set; }
        public string MapContactName22 { get; set; }
        public string MapContactName23 { get; set; }
        public Nullable<bool> DensitySelected1 { get; set; }
        public Nullable<bool> DensitySelected2 { get; set; }
        public Nullable<bool> DensitySelected3 { get; set; }
        public Nullable<bool> DensitySelected4 { get; set; }
        public Nullable<bool> DensitySelected5 { get; set; }
        public Nullable<bool> DensitySelected6 { get; set; }
        public Nullable<bool> DensitySelected7 { get; set; }
        public Nullable<bool> DensitySelected8 { get; set; }
        public Nullable<bool> DensitySelected9 { get; set; }
        public Nullable<bool> DensitySelected10 { get; set; }
        public Nullable<bool> DensitySelected11 { get; set; }
        public Nullable<bool> DensitySelected12 { get; set; }
        public Nullable<bool> DensitySelected13 { get; set; }
        public Nullable<bool> DensitySelected14 { get; set; }
        public Nullable<bool> DensitySelected15 { get; set; }
        public Nullable<bool> DensitySelected16 { get; set; }
        public Nullable<bool> DensitySelected17 { get; set; }
        public Nullable<bool> DensitySelected18 { get; set; }
        public Nullable<bool> DensitySelected19 { get; set; }
        public Nullable<bool> DensitySelected20 { get; set; }
        public Nullable<bool> DensitySelected21 { get; set; }
        public Nullable<bool> DensitySelected22 { get; set; }
        public Nullable<bool> DensitySelected23 { get; set; }
        public int CreaterBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual NetworkInfoContact NetworkInfoContact { get; set; }
    }
}
