//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Plugin.Survey.Core.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyEntities : DbContext
    {
        public SurveyEntities()
            : base("name=SurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NetworkContacts_V> NetworkContacts_V { get; set; }
        public virtual DbSet<NetworkInfoContact> NetworkInfoContacts { get; set; }
        public virtual DbSet<NetworkRelationship> NetworkRelationships { get; set; }
        public virtual DbSet<RelationshipDensity> RelationshipDensities { get; set; }
        public virtual DbSet<ParticipantProfile> ParticipantProfiles { get; set; }
        public virtual DbSet<vWhoKnowWho> vWhoKnowWhoes { get; set; }
        public virtual DbSet<NetworkRelationshipDemo> NetworkRelationshipDemoes { get; set; }
        public virtual DbSet<vCompositeReport> vCompositeReports { get; set; }
    }
}
