//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPI.Plugin.Survey.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCompositeReport
    {
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> MaxDensity { get; set; }
        public Nullable<int> CurrentDensity { get; set; }
        public Nullable<int> TotalParticipants { get; set; }
        public Nullable<int> TotalSurveysCompleted { get; set; }
        public Nullable<decimal> Yield { get; set; }
        public string Gender { get; set; }
        public string AgeGroup { get; set; }
        public string Region { get; set; }
        public string WorkRegion { get; set; }
        public string NativeLanguage { get; set; }
        public string NetworkPercentage { get; set; }
        public Nullable<int> Contacts { get; set; }
        public Nullable<int> StategicContacts { get; set; }
        public Nullable<int> OperationalContacts { get; set; }
        public Nullable<int> DevelopmentalContacts { get; set; }
        public Nullable<int> FEMALE { get; set; }
        public Nullable<int> MALE { get; set; }
        public Nullable<int> RFAsia { get; set; }
        public Nullable<int> RFAfrica { get; set; }
        public Nullable<int> RFCentral { get; set; }
        public Nullable<int> RFEurope { get; set; }
        public Nullable<int> RFMiddleEast { get; set; }
        public Nullable<int> RFNorthAmerica { get; set; }
        public Nullable<int> RFOceania { get; set; }
        public Nullable<int> RFSouthAmerica { get; set; }
        public Nullable<int> SameCompany { get; set; }
        public Nullable<int> SameFunction { get; set; }
        public Nullable<int> SameBusinessUnit { get; set; }
        public Nullable<int> SameLang { get; set; }
        public Nullable<int> Senior { get; set; }
        public Nullable<int> Peer { get; set; }
        public Nullable<int> Junior { get; set; }
        public Nullable<int> Other { get; set; }
        public Nullable<int> C18_24 { get; set; }
        public Nullable<int> C25_34 { get; set; }
        public Nullable<int> C35_44 { get; set; }
        public Nullable<int> C45_54 { get; set; }
        public Nullable<int> C55_64 { get; set; }
        public Nullable<int> C65_ { get; set; }
        public Nullable<int> VeryClose { get; set; }
        public Nullable<int> Close { get; set; }
        public Nullable<int> Distant { get; set; }
        public Nullable<int> NotVeryClose { get; set; }
    }
}
