CREATE TABLE [survey].[NetworkInfoContacts]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ParticipantId] INT NOT NULL, 
    [ContactName1] NVARCHAR(150) NULL, 
    [ContactName2] NVARCHAR(150) NULL, 
	[ContactName3] NVARCHAR(150) NULL, 
    [ContactName4] NVARCHAR(150) NULL, 
    [ContactName5] NVARCHAR(150) NULL, 
    [ContactName6] NVARCHAR(150) NULL, 
	[ContactName7] NVARCHAR(150) NULL, 
    [ContactName8] NVARCHAR(150) NULL, 
	[JobContactName1] NVARCHAR(150) NULL, 
    [JobContactName2] NVARCHAR(150) NULL, 
	[JobContactName3] NVARCHAR(150) NULL, 
    [JobContactName4] NVARCHAR(150) NULL, 
    [JobContactName5] NVARCHAR(150) NULL, 
    [JobContactName6] NVARCHAR(150) NULL, 
	[JobContactName7] NVARCHAR(150) NULL, 
    [JobContactName8] NVARCHAR(150) NULL, 
	[CrrContactName1] NVARCHAR(150) NULL, 
    [CrrContactName2] NVARCHAR(150) NULL, 
	[CrrContactName3] NVARCHAR(150) NULL, 
    [CrrContactName4] NVARCHAR(150) NULL, 
    [CrrContactName5] NVARCHAR(150) NULL, 
    [CrrContactName6] NVARCHAR(150) NULL, 
	[CrrContactName7] NVARCHAR(150) NULL, 
    [CrrContactName8] NVARCHAR(150) NULL, 
	[AllowNewContacts] bit null,
    [CreaterBy] INT NOT NULL, 
    [CreatedOn] DATETIME2 NOT NULL, 
    [ModifiedBy] INT NULL, 
    [ModifiedOn] DATETIME2 NULL
)
