CREATE TABLE [survey].[RelationshipDensity]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ParticipantId] INT NOT NULL, 
    [NetworkContactID] INT NOT NULL, 
	[ContactName] NVarchar(150) NOT NULL, 
	[MapContactName2] NVarchar(150) , 
	[MapContactName3] NVarchar(150) , 
	[MapContactName4] NVarchar(150) , 
	[MapContactName5] NVarchar(150) , 
	[MapContactName6] NVarchar(150) , 
	[MapContactName7] NVarchar(150) , 
	[MapContactName8] NVarchar(150) , 
	[MapContactName9] NVarchar(150) , 
	[MapContactName10] NVarchar(150) , 
	[MapContactName11] NVarchar(150) , 
	[MapContactName12] NVarchar(150) , 
	[MapContactName13] NVarchar(150) , 
	[MapContactName14] NVarchar(150) , 
	[MapContactName15] NVarchar(150) , 
	[MapContactName16] NVarchar(150) , 
	[MapContactName17] NVarchar(150) , 
	[MapContactName18] NVarchar(150) , 
	[MapContactName19] NVarchar(150) , 
	[MapContactName20] NVarchar(150) , 
	[MapContactName21] NVarchar(150) , 
	[MapContactName22] NVarchar(150) , 
	[MapContactName23] NVarchar(150) , 
    [DensitySelected1] BIT NULL, 
    [DensitySelected2] BIT NULL, 
    [DensitySelected3] BIT NULL, 
    [DensitySelected4] BIT NULL, 
    [DensitySelected5] BIT NULL, 
    [DensitySelected6] BIT NULL, 
    [DensitySelected7] BIT NULL, 
    [DensitySelected8] BIT NULL, 
    [DensitySelected9] BIT NULL, 
    [DensitySelected10] BIT NULL, 
    [DensitySelected11] BIT NULL, 
    [DensitySelected12] BIT NULL, 
    [DensitySelected13] BIT NULL, 
    [DensitySelected14] BIT NULL, 
    [DensitySelected15] BIT NULL, 
    [DensitySelected16] BIT NULL, 
    [DensitySelected17] BIT NULL, 
    [DensitySelected18] BIT NULL, 
    [DensitySelected19] BIT NULL, 
    [DensitySelected20] BIT NULL, 
    [DensitySelected21] BIT NULL, 
    [DensitySelected22] BIT NULL, 
    [DensitySelected23] BIT NULL, 
	[CreaterBy] INT NOT NULL, 
    [CreatedOn] DATETIME2 NOT NULL, 
    [ModifiedBy] INT NULL, 
    [ModifiedOn] DATETIME2 NULL, 
    CONSTRAINT [FK_RelationshipDensity_NetworkInfoContacts] FOREIGN KEY ([NetworkContactID]) REFERENCES [survey].[NetworkInfoContacts]([Id]) on delete cascade
)

